### ISSUE TITLE
files couldn't be open

### ISSUE THREAD

**Issue by jackie1234567890** [dindaulima/MSGARCH_ML#1]
i  could not open h5
files with python or R

**Comment by dindaulima** [comment]
I'm sorry it's still under development. 
make sure the path where you saved the model .h5 is right. the path's default value called in the function is different from where I put my model is
and I'm sorry for my poor english 🙏

**Comment by jackie1234567890** [comment]
Thanks a lot. I would like to ask you a question what shoud i do if i want to fit rt of a stock  with msgarch estimators  to get rt hat.    I'm sorry for my poor code.

**Comment by dindaulima** [comment]
for MSGARCH package in R, if you use rt as input, then you get rt hat as the output. To forecast the volatility of the stock then you have to square the rt hat.
I extracted the rt hat of each regime of the msgarch output and squared them (v1, and v2. look at the code in fitLSTM.R) and fit it with machine learning model to get a better prediction of rt_hat^2

**Comment by dindaulima** [comment]
Sorry my answer is kind of confusing, it would be clear if I can write the equation, but I'm still working on it and I'm afraid I can't show it to you anytime soon

**Comment by jackie1234567890** [comment]
thank u for your replay.  I check the code of the MSGARCH package in R ,but  the function FITML and FITMCMC don't output rt hat.  For example, i get the soybean returns rt. rt can be positive or negative. the FITML only output the standard error of  volatility instead of fitted rt hat. Of course, maybe I misunderstood.  I'm interest in the negative rt hat.  but i falled to get it. I would be very grateful if you could give me some useful advice.

**Comment by dindaulima** [comment]
I think you should use egarch to get the negative volatility. There are many restriction in msgarch package in R by Ardia et al  (2019). There are many research which don't use standart type garch to forecast the negative volatility. 
I'm sorry, I don't have any solution for your problem

**Comment by dindaulima** [comment]
Oh maybe you have to fit the ARMA model to get the rt hat, and use the ARMA's residual (at) to fit the msgarch.
and then you can have the rt = rt hat + at hat.
you're gonna get positive at hat from the fitted msgarch by Ardia (2019), but rt hat for ARMA model can be negative

**Comment by jackie1234567890** [comment]
emm，there maybe exists anthor question why at is postive. I guess it's not reasonable.   oh, do u understand the function simulate of MSGARCH packages. could i use the function to solve my issue ?  what should I do if i can?

**Comment by dindaulima** [comment]
I've tried to recode  the MSGARCH by Ardia (2019) using only R function once, since Ardia use C++ to code the equation, but I still use Ardia's function to create the msgarch object. 
I get the same result of the fitted volatility in each regime, but I get different result for the overall volatility. I don't quite understand which part of the estimation process that make the result be so different. 
I'm sorry I don't have the time to upload it in github 
but since i only use the standart garch type model, maybe even my code would give a big differences on your case 🙏

**Comment by jackie1234567890** [comment]
Thank you so much for taking the time to answer my question. Looking forward to your new work.

**Comment by dindaulima** [comment]
I'm the one who should be thankful. Thank you for sparing your time to read my work and reply my answer. I am grateful for your support.  You've made my day :)
